config/routes.rb
Rails.application.routes.draw do
  resources :bus_routes do
    resources :trips, only: [:show]
  end
  root to: 'welcome#index'
  get "connect" => "welcome#connect_to_actransit", :as => "connect_to_actransit"
  get "refresh" => "bus_routes#refresh_bus_routes", :as => "refresh_bus_routes"
end

app/models/bus_route.rb
class BusRoute < ActiveRecord::Base

  def description_to_s
    description_string = self.description
    description_string.slice!("San Francisco - ")
    return description_string
  end

end

app/models/stop.rb
class Stop

  attr_reader :stop_id, :bus_route_id, :trip_id, :name, :latitude, :longitude, :scheduled_time

  def initialize(stop_id, bus_route_id, trip_id, name, latitude, longitude, scheduled_time)
    @stop_id = stop_id
    @bus_route_id = bus_route_id
    @trip_id = trip_id
    @name = name
    @latitude = latitude
    @longitude = longitude
    @scheduled_time = scheduled_time
  end

end

app/models/trip.rb
class Trip

  attr_reader :trip_id, :bus_route_id, :schedule_type, :start_time, :direction

  def initialize(trip_id, bus_route_id, schedule_type, start_time, direction)
    @trip_id = trip_id
    @bus_route_id = bus_route_id
    @schedule_type = schedule_type
    @start_time = start_time
    @direction = direction
  end

  def schedule_type_to_s
    case schedule_type
    when 0
      return "M-F"
    when 5
      return "Sa"
    when 6
      return "Su"
    end
  end

  def start_time_to_s
    return DateTime.parse(start_time).strftime("%I:%M %p")
  end

  def direction_to_s
    bus_route = BusRoute.find(self.bus_route_id)
    if self.direction == "Westbound"
      direction = "To SF"
    else
      direction = "To #{bus_route.description_to_s}"
    end
    return direction
  end

end

app/controllers/bus_routes_controller.rb
class BusRoutesController < ApplicationController
  ACTransitRails.configure(ENV['ACTRANSIT_TOKEN'])

  def index
    @bus_routes = BusRoute.all
  end

  def show
    @bus_route = BusRoute.find(params[:id])
    @fetched_trips = ACTransitRails.get_trips(@bus_route.name)
    @trip_array = []
    @fetched_trips.each do |trip_hash|
      if params[:direction]
        if params[:direction] == "Westbound"
          @direction = "To SF"
        else
          @direction = "To #{@bus_route.description_to_s}"
        end
        if params[:direction] == trip_hash["Direction"]
          new_trip = Trip.new(
            trip_hash["TripId"],
            @bus_route.id,
            trip_hash["ScheduleType"],
            trip_hash["StartTime"],
            trip_hash["Direction"]
          )
          @trip_array << new_trip
        end
      else
        @direction = nil
        new_trip = Trip.new(
          trip_hash["TripId"],
          @bus_route.id,
          trip_hash["ScheduleType"],
          trip_hash["StartTime"],
          trip_hash["Direction"]
        )
        @trip_array << new_trip
      end
    end
    @trip_array.sort_by!{|x| [x.direction, x.schedule_type, x.start_time]}
  end

  def create
    @bus_route = BusRoute.new(bus_route_params)
    @bus_route.save
    redirect_to bus_routes_path
  end

  def refresh_bus_routes
    fetched_routes = ACTransitRails.get_all_routes
    fetched_routes.each do |route|
      if route["Description"].starts_with?("San Francisco -")
        bus_route = BusRoute.where(name: route["Name"]).first
        if bus_route.nil?
          fetched_directions = ACTransitRails.get_directions(route["Name"])
          new_bus_route = BusRoute.new(
            name: route["Name"], 
            description: route["Description"],
            direction_a: fetched_directions[0],
            direction_b: fetched_directions[1]
          )
          new_bus_route.save
        end
      end
    end
    redirect_to(request.referrer || root_path)
  end

  private

  def bus_route_params
    params.require(:bus_route).permit(:name, :description)
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def show
    @bus_route = BusRoute.find(params[:bus_route_id])
    fetched_trips = ACTransitRails.get_trips('@bus_route.name')
    trip_hash = fetched_trips.detect{|trip| trip["TripId"] == params[:id].to_i}
    puts ">>>>>#{trip_hash}"
    @trip = Trip.new(
      trip_hash["TripId"],
      @bus_route.id,
      trip_hash["ScheduleType"],
      trip_hash["StartTime"],
      trip_hash["Direction"]
    )
    fetched_stops = ACTransitRails.get_stops(@bus_route.name, @trip.trip_id)
    puts ">>>>> >>>>> >>>>> #{fetched_stops}"
    @stops_array = []
    # fetched_trips_stops.each do |stop|
    #   new_stop = Stop.new(name: stop["Name"], stop_id: stop["StopId"], latitude: stop["Latitude"], longitude: stop["Longitude"], bus_route: new_bus_route)
    #   @stops_array << new_stop
    # end
  end

end

app/views/bus_routes/_stops_list.html.haml
.stops-list
  - @stops.each do |stop|
    .one-per-line-centered
      .stop-list-entry
        %h2= stop.name
        .grid-layout
          .grid-items
            %p.text-label= "Stop Id:"
            %p= stop.stop_id
          .grid-items
            %p.text-label= "Latitude:"
            %p= stop.latitude.to_s
          .grid-items
            %p.text-label= "Longitude:"
            %p= stop.longitude.to_s

app/views/bus_routes/index.html.haml
%h2 All Transbay Bus Routes
- if @bus_routes.count == 0
  .refresh-routes-link
    = link_to "Refresh Routes", refresh_bus_routes_path
.grid-layout
  - @bus_routes.each do |bus_route|
    .full-length-item
      .bus-route-list-entry
        .route-name-box
          .route-name= link_to bus_route.name, bus_route_path(bus_route)
        .direction-b-box
          .direction-button= link_to "To SF", bus_route_path(bus_route, :direction => bus_route.direction_b)
        .direction-a-box
          .direction-button= link_to "To #{bus_route.description_to_s}", bus_route_path(bus_route, :direction => bus_route.direction_a)

app/views/bus_routes/show.html.haml
%h2.text-center= @bus_route.name + " - #{@direction} Trips"
.grid-layout
  - @trip_array.each do |trip|
    .full-length-item
      .trip-list-entry
        .start-time-box
          .start-time= link_to trip.start_time_to_s, bus_route_trip_path(@bus_route, trip.trip_id)
        .trip-direction-box
          .trip-direction=  trip.direction_to_s
        .schedule-type-box
          .schedule-type= trip.schedule_type_to_s

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BayCrosser
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %h1= link_to "BayCrosser", root_path
      .all-routes-link= link_to "All Routes", bus_routes_path
    .container
      = yield

app/views/trips/_list_entry.html.haml
.trip-list-item
  .trip-list-entry
    .grid-layout
      .col-sm-12.text-center
        %h4= trip.direction
    .grid-layout
      .trip-list-entry-item
        %p.text-center= trip.schedule_type_to_s
      .trip-list-entry-item
        %p.text-center= trip.start_time_to_s

app/views/trips/show.html.haml
%p= @trip.trip_id

app/views/welcome/index.html.haml
%h2 Welcome to BayCrosser
%p BayCrosser is a minimal web app for accessing up-to-date ACTransit Transbay Bus Schedules for the San Francisco, Bay Area
%h2 About
%p 
  Baycrosser was developed by Sanjay Patel to demonstrate the 
  =link_to "actransit_rails gem.", "https://rubygems.org/gems/actransit_rails/versions/0.2.0"